owner: jm-sky
repo: upptime # nazwa repozytorium

sites:
  - name: Redis Upstash
    url: https://divine-robin-10727.upstash.io
  - name: S3 SCW
    url: https://s3.pl-waw.scw.cloud
  - name: Soketi
    url: https://saasbase-soketi.fly.dev
  - name: OpenRouter
    url: https://openrouter.ai
